---
services:
  build:
    context: ./docker
  volumes:
    - app:/var/boxfuse-sample-java-war-hello/target

  tomcat:
    image: tomcat:8-alpine
    ports:
      - 8080:8080
    volumes:
      - app:/usr/local/tomcat/webapps

volumes:
  app:
